[[cover]]
bg-image = "artwork.jpg"
centre-text = true
colour-gradient = "5"
do-not-greyscale = true
gradient-opacity = 30
main-text = "Rahasin Wage "
sub-text = "Olu Wasanthi"
sub-text-above = true

[config]
output-size = 800
